#!/usr/bin/env python
#coding: utf-8
def main():
    try:
        while 1: 
            print "\033[92m input your sequence->",
            seq = raw_input()
            print "\033[0m  reverse complement->",
            print "".join(map(lambda x: {"A":"T","C":"G","G":"C","T":"A"}[x] \
                if x in ["A","T","C","G"] else "N", reversed(list(seq.upper()))))
    except KeyboardInterrupt:
        print "\033[0m ",

if __name__ == '__main__':
    main()
